name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::508075578001:role/iam-harshit
          aws-region: ap-south-1

      - name: Build SAM App
        run: sam build

      - name: Deploy SAM App
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
